CREATE DATABASE enriquevs;

USE enriquevs;

CREATE TABLE Track (
    Id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(200) NOT NULL,
    Length INT(3)
);

CREATE TABLE Album (
	Id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(200) NOT NULL,
    TrackId INT,
    FOREIGN KEY (TrackId) REFERENCES Track(Id)
);

CREATE TABLE Artist (
	Id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(200) NOT NULL,
    AlbumId INT,
    FOREIGN KEY (AlbumId) REFERENCES Album(Id)
);

CREATE TABLE Collection (
	Id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(200) NOT NULL,
    ArtistId INT,
    FOREIGN KEY (ArtistId) REFERENCES Artist(Id)
);
